export * from './auth.routes'
export * from './priority.routes'
export * from './project.routes'
export * from './status.routes'
export * from './task.routes'
export * from './type.routes'
export * from './user.routes'
